[package]
name = "mcsast"
authors = ["MagicTeaMC <maoyue@maoyue.tw>"]
description = "Manage Minecraft server / proxy quickly and easily!"
version = "2.2.2"
edition = "2024"
license = "GPL-3.0"

homepage = "https://github.com/MagicTeaMC/Minecraft-server-auto-setup"
repository = "https://github.com/MagicTeaMC/Minecraft-server-auto-setup"
readme = "README.md"
keywords = ["gamedev", "minecraft"]
categories = ["command-line-utilities"]
exclude = ["images/"]

[dependencies]
clap = { version = "4.5", features = ["derive"] }
colored = "3.0"
inquire = "0.7"
reqwest = { version = "0.12", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"