[package]
name = "Minecraft-server-auto-setup"
version = "2.0.0-SNAPSHOT"
edition = "2021"

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
colored = "2.1.0"
inquire = "0.7.5"
reqwest = { version = "0.12.7", features = ["blocking", "json"] }
serde_json = "1.0.127"