[package]
name = "Minecraft-server-auto-setup"
version = "2.0.0-SNAPSHOT"
authors = ["Maoyue <maoyue@maoyue.tw>"]

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
