name: Build

on:
  push:
    branches: [v2]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
            target: [x86_64-unknown-linux-musl, x86_64-pc-windows-gnu, x86_64-apple-darwin]
    steps:
      - uses: actions/checkout@master
      - name: Set macOS SDK version
        run: echo "MACOSX_DEPLOYMENT_TARGET=10.12" >> $GITHUB_ENV
      - name: Compile
        id: compile
        uses: rust-build/rust-build.action@v1.4.5
        with:
          RUSTTARGET: ${{ matrix.target }}
          UPLOAD_MODE: none
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Binary
          path: |
            ${{ steps.compile.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile.outputs.BUILT_CHECKSUM }}