name: Build

on:
  push:
    branches: [v2]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        target: [x86_64-apple-darwin, aarch64-apple-darwin]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Rust
        run: rustup target add ${{ matrix.target }}
      
      - name: Set environment variables
        run: |
          export LC_ALL=en_US.UTF-8
          export LANG=en_US.UTF-8
      
      - name: Compile
        run: cargo build --release --target ${{ matrix.target }}
      
      - name: Upload artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: Binary-${{ matrix.target }}
          path: |
            target/${{ matrix.target }}/release/Minecraft-server-auto-setup